// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace onlinebookstorev1._0
{
    public partial class AuthersBook
    {
        public int BookId { get; set; }
        public int AutherId { get; set; }

        public virtual Authers Auther { get; set; }
        public virtual Books Book { get; set; }
    }
}