// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace onlinebookstorev1._0
{
    public partial class Authers
    {
        public int AutherId { get; set; }
        public string AutherName { get; set; }
        public string AutherImageUrl { get; set; }
        public virtual ICollection<AuthersBook> authersbook { get; set; }
    }
}