// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using onlinebookstorev1._0.Modals;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace onlinebookstorev1._0
{
    public partial class Books
    {
        public int BookId { get; set; }
        public string ISBN { get; set; }//*
        public string Title { get; set; }//*

        public string publisher { get; set; }
        public int pageCount { get; set; }
        [ForeignKey("dimension")]
        public int dimension_Id { get; set; } 
        public DateTime PublishedDate { get; set; }
        public string Description { get; set; }
        public int CoverImageId { get; set; }
        public virtual ICollection<AuthersBook> authersbook { get; set; }
        public virtual CoverImages CoverImage { get; set; }
        public virtual dimensions dimension { get; set; }
        public string language { get; set; }
        public virtual ICollection<BooksCategorie> BooksCategories { get; set; }
        public virtual ICollection<products> Products { get; set; }
       
    }
}