// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace onlinebookstorev1._0
{
    public partial class CoverImages
    {
        

        public int CoverImageId { get; set; }
        public string Coverimage { get; set; }

        
    }
}